/**
 * ICMR STS Research Study — Phase 1 Type Definitions
 * Study: "Association Between Meal Timing, Chronotype, and Heart Rate Variability Among Undergraduate Medical Students"
 */

export interface GoogleFormSubmissionPayload {
  submission_id: string;        // Unique form response ID or row hash
  participant_id?: string;      // Generated by Apps Script (e.g. STS-2026-XXXXXX)
  form_timestamp: string;       // ISO timestamp from Google Sheet
  raw_answers: Record<string, string | number>; // Keyed by column headers
  normalized_data: NormalizedQuestionnaireData;
  metadata: {
    sheet_name?: string;
    row_number?: number;
    script_version: string;
    environment: 'production' | 'staging' | 'test';
  };
}

export interface NormalizedQuestionnaireData {
  // Section 1: Participant Information & Consent
  consent_agreement: 'Yes' | 'No';
  has_chronic_illness: 'Yes' | 'No';
  is_on_medications: 'Yes' | 'No';

  // Section 2: Demographic Details (Logical separation of Direct Identifiers)
  identifiers: {
    participant_id: string;
    name_optional?: string;
    contact_number?: string;
  };

  // Section 2 & 3 & 4 & 5: Research Dataset (De-identified)
  research: {
    participant_id: string;
    age_years: number;
    gender: 'Male' | 'Female' | 'Prefer not to say' | string;
    mbbs_year: 'First MBBS' | 'Second MBBS' | string;
    height_cm: number;
    weight_kg: number;
    bmi?: number; // Weight (kg) / (Height(m))^2

    // Meal Timing
    breakfast_time: string;
    breakfast_skipped_days_per_week: string;
    dinner_time: string;
    night_snack_frequency: string;
    eating_duration_window: string;
    regular_meal_timings: string;

    // rMEQ Questions & Raw Scores
    rmeq_q1_wake_time: string;
    rmeq_q2_tiredness: number | string;
    rmeq_q3_bedtime_tired: string;
    rmeq_q4_morning_ease: number | string;
    rmeq_q5_peak_time: string;
    rmeq_total_score?: number;
    chronotype_category?: 'Morning type' | 'Intermediate type' | 'Evening type';

    // Lifestyle Factors
    sleep_duration: string;
    caffeine_frequency: string;
    physical_activity_level: string;
  };
}

export interface WebhookResponse {
  success: boolean;
  participant_id: string;
  submission_id: string;
  received_at: string;
  audit_event_id: string;
  status: 'QUEUED_FOR_CRF_GENERATION' | 'INELIGIBLE_DECLINED_CONSENT' | 'VALIDATED';
  message: string;
  warnings?: string[];
}

export interface SecurityAuditRecord {
  event_id: string;
  timestamp: string;
  event_type: 'FORM_SUBMITTED' | 'PARTICIPANT_ID_CREATED' | 'SECURITY_VERIFICATION_FAILED';
  participant_id: string;
  submission_id: string;
  actor_type: 'GOOGLE_APPS_SCRIPT' | 'SYSTEM';
  client_ip_hash?: string;
  status: 'SUCCESS' | 'REJECTED';
  metadata: {
    reason?: string;
    has_consent: boolean;
    duration_ms?: number;
  };
}
